# Generated by Django 5.0.2 on 2024-03-06 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            (
                                "50 mins Online Therapy- Individual",
                                "50 mins Online Therapy Individual",
                            ),
                            (
                                "50 mins Online Therapy- Couples",
                                "50 mins Online Therapy- Couples",
                            ),
                        ],
                        default="50 mins Online Therapy- Individual",
                        max_length=50,
                    ),
                ),
                ("day", models.DateField(default=django.utils.timezone.now)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("8 AM", "8 AM"),
                            ("9 AM", "9 AM"),
                            ("10 AM", "10 AM"),
                            ("11 AM", "11 AM"),
                            ("12 PM", "12 PM"),
                            ("1 PM", "1 PM"),
                            ("2 PM", "2 PM"),
                            ("3 PM", "3 PM"),
                            ("4 PM", "4 PM"),
                            ("5 PM", "5 PM"),
                            ("6 PM", "6 PM"),
                            ("7 PM", "7 PM"),
                            ("8 PM", "8 PM"),
                        ],
                        default="8 AM",
                        max_length=10,
                    ),
                ),
                ("time_ordered", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
